### ISSUE TITLE
Make the grid system work with 1170 columns

### ISSUE THREAD

**Issue by ricardofiorani** [impressivewebs/HTML9-Responsive-Boilerstrap-js#106]
So instead of wasting time and struggling trying to fix your row width, you could set one column per pixel, so if you want a container (or row, etc..) of 500px of width, just set it to 500 columns, or add the class col-md-500.

**Comment by CrossEye** [comment]
@ricardofiorani: Closing this?  Really?  This is an important issue to many in the H9RB community.  And it hasn't even been five years since the last activity!  What are you thinking?
