### ISSUE TITLE
Doesn't seem to work when I'm viewing the framework within AOL software

### ISSUE THREAD

**Issue by robstemmtp** [impressivewebs/HTML9-Responsive-Boilerstrap-js#123]
This doesn't seem to load when viewing within the AOL application I installed from the 100 free hours disc. Any thoughts on how to fix this issue?

**Comment by Rrrapture** [comment]
I ran into a similar issue:
 - First, shut down your computer. 
 - Turn on the radio or a similar music-playing device--slow jams work best. 
- Finally, turn your computer back on and restart the AOL browser. 

This should fix the problem.

**Comment by robstemmtp** [comment]
That Totally Worked! Plus it site says "You've Got Mail!" every time the framework loads. Amazing! Thanks for your help
