### ISSUE TITLE
After installation, Node.js has turned into ColdFusion Server

### ISSUE THREAD

**Issue by chrisath80** [impressivewebs/HTML9-Responsive-Boilerstrap-js#125]
I brutally repocloned the master git into my local .dev environment and I got a system message saying that 'Your Node.js server has been update to ColdFusion. Please update your application by using the "rescheme cf-node apps -r" in your working directory".

Any ideas?

**Comment by raiseandfall** [comment]
@chrisath80 You should probably clear your browser cache.

**Comment by cobalamin** [comment]
This is a serious issue that I've run across, on average, 7 times per cloud deployment. The biggest problem for us was that our service of choice, CloudDudes Ltd., charges twice for ColdFusion servers.
We've only been able to solve this by tearing down all cloud instances and containerizing everything, and then redeploying with `npm install fake-coldfusion --save-deps`, so far CloudDudes haven't noticed, but I'm not sure what will happen when they do.

In any case, this has caused us huge monetary issues and we've switched to a custom build of MooTools for the time being.

**Comment by chrisath80** [comment]
@raiseandfall I asked from the internet.com to restart the whole internet and after that it worked. Thanks mate!

@cobalamin from all the hosting providers, I prefer hostchopper (more info here: http://laughingsquid.com/host-chopper-a-hilarious-web-hosting-parody/)

**Comment by cobalamin** [comment]
I just called the people at internet.com, thanks @chrisath80. They have been incredibly helpful to me as well, and all seems fixed. Issue can be closed :+1:

**Comment by chrisath80** [comment]
@cobalamin issue closed. The internets are working again.
