### ISSUE TITLE
Boilerstrap integration with applescript 3.1.990 crashing server problem

### ISSUE THREAD

**Issue by cresharper** [impressivewebs/HTML9-Responsive-Boilerstrap-js#138]
HI - I'm having some trouble with this framework for the past couple of months. I'm building an MVC supercontroller app application app based off of npm angular node foundation marsupial JS and am building off of Applescript 3.1.9.90, and it's crashing my NGINX KMLQ server. I have tried re-installing grulpnt several times through NPM as well as uninstall jQuery and writing CSS1 fallbacks. It's also important to note that this requires Netscape 2.0 and IE4 compatibility. So I tried running this command:

    sudo --install boilerstrapjs ----xcdnj -gem -r

But it does not fix the issue.

For what it's worth, I am on a Windows 1976 machine running on a 4 disk drive with 1MB of ram. So I'm thinking it could be that? I'm also wondering if I need to uninstall my HTML9 server side compiler and re-factor my library so it supports EspressoScript and can authenticate tokens from the Google API...

Any help is appreciated!

**Comment by CrossEye** [comment]
Have you tried cross-compiling the ReduxFaces gemfile?  Sometimes I've found that helps with pre-1979 versions of Windows.

**Comment by cresharper** [comment]
Hey @CrossEye thanks for the response. I cross-compiled my reduxfaces and g0t this error:

    fatal error death: sudden expectation line 3501 boilerstrap.js(00000.1.1.1.1.1.1.1.1.1 exec: no) 

but I remembered to attackmarge my repo after my html9 serverside compiled and resolved a JS error 31. now I'm up and running!

**Comment by CrossEye** [comment]
@cresharper: Wow, very interesting!  I've never heard of anyone having to attackmarge in this case on anything but a POSWinMacIX machine.  I guess if you live long enough, you'll see everything!  Next we know, someone's going to end up having to double-reverse grep the hypercore.  Wouldn't that be a hoot?
