### ISSUE TITLE
Issue when running in parallel universe Omega_Cassiopeia#54365

### ISSUE THREAD

**Issue by avitron01** [impressivewebs/HTML9-Responsive-Boilerstrap-js#152]
Division by zero seems to be giving finite values. Not buying the whole cross universe compatible thing -_-

**Comment by CrossEye** [comment]
This is a known issue in the O_C series 53992 - 55721.  I'm afraid you'd have to ask them to update their firmware.  But good luck with that.  The lead dev was heard for months muttering something about "zero divided by zero is too defined: it's everything, damn it!" and then wandering around poking chickens with sticks.  They seem to have proceeded without him in the 56000+ versions<sup>*</sup>, so maybe it's okay now.

----------

<sup>*</sup> If you want to visit him in the Institute, I head he loves it when people bring him fruitcake and functors.

**Comment by avitron01** [comment]
Ah yeah, you're right! The firmware we're using dates back to 0.0042 pico seconds after the Big Bang. Should have listened to Carl Sagan's cosmic space voice, it was a sign all along. Thanks for all the help.

Live Long And Prosper 🖖

**Comment by CrossEye** [comment]
Oh wow, I'd forgotten that the O_C series included Big Bangs; I've got to get out the the sticks more often.
