### ISSUE TITLE
Issue with DI of EmberOnKebabs v25 and DollLubricator v0.0.6.5.324a

### ISSUE THREAD

**Issue by zeknoss** [impressivewebs/HTML9-Responsive-Boilerstrap-js#153]
When I try to lubricate my EmberOnKebabs project using DollLubricator for DI purposes I get the following error:

--UnknownLubricateException: DI failed while EmberOnKebabs integration with DollLubricator. Please dry your console.

What should I do?

**Comment by CrossEye** [comment]
If you're going to use alpha versions, you have to expect things like this.  Try applying some `ConsoleRag`s, or switch to the stable version.

**Comment by zeknoss** [comment]
Thank you, I will do that.
