### ISSUE TITLE
Not running on ATmega8 @16megahearts

### ISSUE THREAD

**Issue by qbasic16** [impressivewebs/HTML9-Responsive-Boilerstrap-js#154]
See title.
I tried to run it on my ATmega8 supercomputer but now the flash is overflowing and not even overclocking to 16.1 megaherts helped.
Help please. My boss will kill me if I don't get this up and running until this Friday 5pm.

**Comment by avitron01** [comment]
I would suggest you to order a can of liquid nitrogen and a big can of lube. ATmega8 is known to use quantum buttanglement and overfucks upto 20.69 megahertz when cooled using liquid nitrogen. If nothing works, use the lube coz you're fucked.

**Comment by qbasic16** [comment]
Thank you so much, it works!
I had to use liquid nitrogen, overclock it to 69.420 megahurts and spread some lube between the legs of the DIP package.

Now I can finally crossspace render HTML10 on gradle of filth with CSS6 in a dockerized cockerblocker package.
Finally TSify runs all SELECT queries on 60fps!

My boss will love this simple little trick...

**Comment by avitron01** [comment]
Nice! The ATmega8 is a box full of wonders. I'm actually hyped about ATmega9. They say it can spawn daemon and open portals to hell. 11/10 would see Satan again.
