### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by PerhapsSomeone** [impressivewebs/HTML9-Responsive-Boilerstrap-js#158]
There's not nearly enough jQuery libraries included! We need to call all of them at least twenty times!

**Comment by alexgarrett** [comment]
Please don't be silly. The maintainers are obviously trying to keep this as lightweight as possible. If you need jQuery support, copy all the plugins to `jquery.plugins.[project-name].js` and FTP them to your server.

Make sure to include the script tag in the header.

**Comment by PerhapsSomeone** [comment]
Thanks for the suggestion! I have included jQuery twenty times now, for good measure.
