### ISSUE TITLE
Please add integration with wasm!

### ISSUE THREAD

**Issue by enoh-barbu** [impressivewebs/HTML9-Responsive-Boilerstrap-js#165]
We need to fast enough also

**Comment by CrossEye** [comment]
@enoh-barbu:

Why did you close this issue?  It was barely in it's prime.

The Turtle-Snail Agile team just last month agreed to consider opening an issue to schedule a tentative vote on whether to bring this question to the pre-planning meeting for the subcommittee on potential new features.  We should have a first draft of their tentative decision by the time of bovine arrival.

**Comment by enoh-barbu** [comment]
welp, yes why not? I guess we need to push this somehow to the committee. If accepted, we'll finally have a platform for no-code/low-code up and running.

**Comment by joeytwiddle** [comment]
I have spoken privately to the secretary for the chair of the triage department, and have been assured that this issue will be fast-tracked into the agenda of the HTML9 Conference's "Future Directions" track, pigeonholed for Q3 2022.

The conference team are very efficient, and have assured me that even if the issue is not discussed during the 3-day forum, it will definitely appear in the programme.

I hope that is fast enough for you!

**Comment by enoh-barbu** [comment]
@joeytwiddle that's awesome! Thanks for the update. My life just got a new sense now. ❤️❤️

😁

**Comment by CrossEye** [comment]
@joeytwiddle: Thank you for the amazing dedication and your unbelievable speed in getting this before the committee.  I am very impressed, so please take the following in the constructive spirit in which is was intended:

There are processes in place for a reason.  The secretary to the chair is *not* the chair herself.  She does not have the formal authority to add something to the agenda, never mind "fast-tracking" it.  If she does manage to place it on that agenda (and we'll see about that), the committee will have to drop something else.  All those items already on the agenda have gone through the five-tier approval process and were available for public comment during the full fifteen-month period.  You do realize that this includes production-critical bugs, right?  This process is described in detail in Volume XVII of the systems manual.  If you haven't read through that, please do so.  The chief deputy undersecretary to the vice-chair of the rules committee has the full set available if you need them.

So, again, thank you for your dedication, but please don't go promising inordinate speed for processing requests.

**Comment by enoh-barbu** [comment]
omg, I'm lost 😁😁
