### ISSUE TITLE
what

### ISSUE THREAD

**Issue by undrafted** [impressivewebs/HTML9-Responsive-Boilerstrap-js#173]

**Comment by CrossEye** [comment]
when?

**Comment by undrafted** [comment]
thank

**Comment by marcus-at-localhorst** [comment]
please reopen

**Comment by undrafted** [comment]
ok this library does not bring me joy

**Comment by CrossEye** [comment]
This is no mere "library".  It is a state of mind.  It is the camel that broke the straw's back.  It is the beginning of the end and the end of the beginning.  It is the final lick before the center of the tootsie pop.  It is the comparison to a summer's day.  It knows what evil lurks in the heart of the Shadow.

**Comment by jedwards1211** [comment]
It's the camel's nose so far in the tent it went out the other side

**Comment by marcus-at-localhost** [comment]
it's not resolved yet, please reopen!
