### ISSUE TITLE
Add support for an AI based blockchain technology  to 3D print big data

### ISSUE THREAD

**Issue by bkb3** [impressivewebs/HTML9-Responsive-Boilerstrap-js#175]
My current startup utilizes an AI based blockchain technology to sell Internet of Things (IoTs) by 3D printing big data from the cloud. I hacked together a custom RSA 2048 bit jquery for the AI frontend while the actual AI uses rust in the backend inside a kubernets pod and it does not work well with this framework.  I tried to run the provided script with `ETH`  from #157 and it runs OK. However AI is still missing #150. pls fix this.

**Comment by CrossEye** [comment]
I believe that was fixed during the transition from little data to BIG DATA.  Please see if any of the Intermediate Data builds work for you.

**Comment by bkb3** [comment]
Thanks for the quick response. `--run-AI quick` option leveraged agile frameworks to provide a robust synopsis for high level overviews. I had to look through the documentation though. 
boilerstrap.js based Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition drivers for our 3D printer was just slick and snappier then the ones written in ANSI C. It organically grew the holistic world view of disruptive innovation via workplace diversity and empowerment.  We could finally override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. 
`--build-blockchain yes --print-big-data fast --my-body-is-ready true` efficiently unleashed cross-media information without cross-media value and quickly maximized timely deliverables for real-time schemas. `--connect-iot` param dramatically maintained clicks-and-mortar solutions without functional solutions. 

10/10 highly recommended for enterprise!
