### ISSUE TITLE
HMTL9RBSJS Framebase violates RFC#58031-KFC

### ISSUE THREAD

**Issue by benscholler** [impressivewebs/HTML9-Responsive-Boilerstrap-js#8]
Have you considered rewriting the jumplink abstraction to an applification of all prefixes? You could do a branch merge garbage collection on the hotswapping plugin hash to reframe your master cypher.

**Comment by CrossEye** [comment]
The good die young.

I can't believe this crucial issue was wantonly destroyed months before its tenth birthday.

What a world.  What a cruel, cruel world.

**Comment by joeytwiddle** [comment]
This is a typical millennial hipster approach, which creates more problems than it solves.

Just use a pipe.
